"""Convert the Energy Rating TV register CSV into assets/data/tv-models.js.

Run from anywhere:  python tools/convert-tv-data.py
To use another dataset, change SOURCE below and re-run.
"""
import csv
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "dataset" / "tv_2026_10_03.csv"
OUTPUT = ROOT / "assets" / "data" / "tv-models.js"


def main():
    with open(SOURCE, encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))

    # Brands that differ only by capitalisation ("Kogan"/"KOGAN") share the most common spelling.
    brand_name = {}
    for name, _ in Counter(r["Brand_Reg"].strip() for r in rows).most_common():
        brand_name.setdefault(name.upper(), name)

    # A (brand, model) pair can be registered more than once: keep the latest expiry date.
    latest = {}
    for r in rows:
        key = (r["Brand_Reg"].strip().upper(), r["Model_No"].strip().upper())
        if key not in latest or r["ExpDate"] > latest[key]["ExpDate"]:
            latest[key] = r

    models = sorted(
        (
            {
                "brand": brand_name[r["Brand_Reg"].strip().upper()],
                "model": r["Model_No"].strip(),
                "tech": r["Screen_Tech"].strip(),
                "sizeIn": round(float(r["screensize"]) / 2.54),
                "watts": float(r["Avg_mode_power"]),
                "labelKwh": float(r["Labelled energy consumption (kWh/year)"]),
                "stars": float(r["Star2"]),
            }
            for r in latest.values()
        ),
        key=lambda m: (m["brand"].upper(), m["model"].upper()),
    )

    lines = ",\n".join("  " + json.dumps(m, ensure_ascii=False) for m in models)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        f"// Generated by tools/convert-tv-data.py from {SOURCE.name}. Do not edit by hand.\n"
        f"const TV_MODELS = [\n{lines}\n];\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(models)} models to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
